---

- block:
    - name: Create zones.conf
      become: yes
      template:
        src: "zones.conf.j2"
        dest: "/etc/icinga2/zones.conf"
        owner: "{{ icinga2_cluster_icinga_user }}"
        group: "{{ icinga2_cluster_icinga_user }}"
        mode: "0640"

    - name: Set constant NodeName
      become: yes
      lineinfile:
        path: "/etc/icinga2/constants.conf"
        regexp: 'const NodeName = ".+"'
        line: 'const NodeName = "{{ common_name }}"'

    - name: Set constant ZoneName
      become: yes
      lineinfile:
        path: "/etc/icinga2/constants.conf"
        regexp: 'const ZoneName = ".+"'
        line: 'const ZoneName = "{{ common_name }}"'

    - name: Set API port for current node
      set_fact:
        icinga2_cluster_current_node_port: "{{ item.port | default(icinga2_cluster_port) }}"
      loop: "{{ lookup('subelements', icinga2_cluster_zones, 'endpoints') | flatten }}"
      when:
        - item.host is defined
        - item.host == inventory_hostname

    - name: Set up API feature
      become: yes
      template:
        src: "api.conf.j2"
        dest: "/etc/icinga2/features-available/api.conf"
        owner: "{{ icinga2_cluster_icinga_user }}"
        group: "{{ icinga2_cluster_icinga_user }}"
        mode: "0644"

    - name: Activate API feature
      become: yes
      file:
        state: link
        src: "/etc/icinga2/features-available/api.conf"
        dest: "/etc/icinga2/features-enabled/api.conf"
        owner: "{{ icinga2_cluster_icinga_user }}"
        group: "{{ icinga2_cluster_icinga_user }}"
      when:
        - inventory_hostname != icinga2_cluster_ca_node
        - ansible_fqdn != icinga2_cluster_ca_node


  notify: "restart_icinga2"
